# Segmenting and Clustering Neighborhoods in Toronto

In [2]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.1.1f             |       h516909a_0         2.1 MB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    ca-certificates-2019.11.28 |       hecc5488_0         145 KB  conda-forge
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    branca-0.4.0               |             py_0          26 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    certifi-2019.11.28         |   py36h9f0ad1d_1         149 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

    altair:          4.1.0-py_1        conda-forge
    branca:          0.4.0-py_0        conda-forge
    folium:          0.5.0-py_0        conda-forge
    python_abi:      3.6-1_cp36m       conda-forge
    vincent:         0.4.4-py_1        conda-forge

The following packages will be UPDATED:

    certifi:         2019.11.28-py36_0             --> 2019.11.28-py36h9f0ad1d_1 conda-forge
    openssl:         1.1.1e-h7b6447c_0             --> 1.1.1f-h516909a_0         conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2020.1.1-0                    --> 2019.11.28-hecc5488_0     conda-forge


Downloading and Extracting Packages
openssl-1.1.1f       | 2.1 MB    | ##################################### | 100%
python_abi-3.6       | 4 KB      | ##################################### | 100%
ca-certificates-2019 | 145 KB    | ##################################### | 100%
vincent-0.4.4        | 28 KB     | ##################################### | 100%
branca-0.4.0         | 26 KB     | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
certifi-2019.11.28   | 149 KB    | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Libraries imported.

Let's load the data.

In [3]:
from bs4 import BeautifulSoup

req = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(req.content,'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table))
neighborhood=pd.DataFrame(df[0])

In [4]:
#Drop NA values
data = df[0].dropna()

In [5]:
data.index.name = None

In [6]:
#Reset index
data = data.reset_index(drop=True)

In [7]:
data.head()

  Postal code           Borough                                  Neighborhood
0         M3A        North York                                     Parkwoods
1         M4A        North York                              Victoria Village
2         M5A  Downtown Toronto                    Regent Park / Harbourfront
3         M6A        North York             Lawrence Manor / Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [8]:
#Shape
data.shape

(103, 3)

## (2) Get the latitude and the longitude coordinates of each neighborhood.

In [9]:
import pandas as pd
df = pd.read_csv('http://cocl.us/Geospatial_data')

In [10]:
df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [11]:
merge = pd.merge(left=data, right=df, how='left', left_on='Postal code', right_on='Postal Code')
merge.head()

,Postal code,Borough,Neighborhood,Postal Code,Latitude,Longitude
0,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
1,M4A,North York,Victoria Village,M4A,43.725882,-79.315572
2,M5A,Downtown Toronto,Regent Park / Harbourfront,M5A,43.654260,-79.360636
3,M6A,North York,Lawrence Manor / Lawrence Heights,M6A,43.718518,-79.464763
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government,M7A,43.662301,-79.389494

In [12]:
geo = merge.drop('Postal Code', axis = 1)
geo.head()

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,Regent Park / Harbourfront,43.654260,-79.360636
3,M6A,North York,Lawrence Manor / Lawrence Heights,43.718518,-79.464763
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government,43.662301,-79.389494

## (3) Explore and cluster the neighborhoods in Toronto.

In [13]:
address = 'toronto'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto are 43.6534817, -79.3839347.

Create a map of Toronto with neighborhoods superimposed on top.

In [14]:
# create map of Toronto using latitude and longitude values
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=10)

%matplotlib inline 

# add markers to map
for lat, lng, borough, neighborhood in zip(geo['Latitude'], geo['Longitude'], geo['Borough'], geo['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
    
map_toronto

Define Foursquare Credentials and Version

In [15]:
CLIENT_ID = 'VK0NAR0DGLAYCBWE5H43PW3EWLWTFNSRGG4NW33NTPN5SUWY' # your Foursquare ID
CLIENT_SECRET = '0FD0MQGZDMZCDQXDE5FSQKFDLI0432TUX32DWUHKACTIXTUL' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: VK0NAR0DGLAYCBWE5H43PW3EWLWTFNSRGG4NW33NTPN5SUWY
CLIENT_SECRET:0FD0MQGZDMZCDQXDE5FSQKFDLI0432TUX32DWUHKACTIXTUL

Let's explore the first neighborhood in our dataframe. Get the neighborhood's name.

In [16]:
geo.loc[0, 'Neighborhood']

'Parkwoods'

Get the neighborhood's latitude and longitude values.

In [17]:
neighborhood_latitude = geo.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = geo.loc[0, 'Longitude'] # neighborhood longitude value

neighborhood_name = geo.loc[0, 'Neighborhood'] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name, 
                                                               neighborhood_latitude, 
                                                               neighborhood_longitude))

Latitude and longitude values of Parkwoods are 43.7532586, -79.3296565.

Now, let's get the top 100 venues that are in Marble Hill within a radius of 500 meters. First, let's create the GET request URL. Name your URL url.

In [18]:
LIMIT = 100 # limit of number of venues returned by Foursquare API

radius = 500 # define radius

# create URL
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=VK0NAR0DGLAYCBWE5H43PW3EWLWTFNSRGG4NW33NTPN5SUWY&client_secret=0FD0MQGZDMZCDQXDE5FSQKFDLI0432TUX32DWUHKACTIXTUL&v=20180605&ll=43.7532586,-79.3296565&radius=500&limit=100'

Send the GET request and examine the resutls

In [19]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5e871fefb57e88001b3dc4c5'},
 'response': {'warning': {'text': "There aren't a lot of results near you. Try something more general, reset your filters, or expand the search area."},
  'headerLocation': 'Parkwoods - Donalda',
  'headerFullLocation': 'Parkwoods - Donalda, Toronto',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 3,
  'suggestedBounds': {'ne': {'lat': 43.757758604500005,
    'lng': -79.32343823984928},
   'sw': {'lat': 43.7487585955, 'lng': -79.33587476015072}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4e8d9dcdd5fbbbb6b3003c7b',
       'name': 'Brookbanks Park',
       'location': {'address': 'Toronto',
        'lat': 43.751976046055574,
        'lng': -79.33214044722958,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.751976046055574,
          'lng': -79.33214044722958}],
        'distance': 245,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['Toronto', 'Toronto ON', 'Canada']},
       'categories': [{'id': '4bf58dd8d48988d163941735',
         'name': 'Park',
         'pluralName': 'Parks',
         'shortName': 'Park',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4e8d9dcdd5fbbbb6b3003c7b-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '53e72d92498e336f61db5bf5',
       'name': 'GTA Restoration',
       'location': {'address': '18 Valley Woods Road #414',
        'lat': 43.753396155415686,
        'lng': -79.33347702026367,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.753396155415686,
          'lng': -79.33347702026367}],
        'distance': 307,
        'postalCode': 'M3A 0A1',
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['18 Valley Woods Road #414',
         'Toronto ON M3A 0A1',
         'Canada']},
       'categories': [{'id': '52f2ab2ebcbc57f1066b8b3a',
         'name': 'Fireworks Store',
         'pluralName': 'Fireworks Stores',
         'shortName': 'Fireworks Store',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/default_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-53e72d92498e336f61db5bf5-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4cb11e2075ebb60cd1c4caad',
       'name': 'Variety Store',
       'location': {'address': '29 Valley Woods Road',
        'lat': 43.75197441585782,
        'lng': -79.33311418516017,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.75197441585782,
          'lng': -79.33311418516017}],
        'distance': 312,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['29 Valley Woods Road', 'Toronto ON', 'Canada']},
       'categories': [{'id': '4bf58dd8d48988d1f9941735',
         'name': 'Food & Drink Shop',
         'pluralName': 'Food & Drink Shops',
         'shortName': 'Food & Drink',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/foodanddrink_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4cb11e2075ebb60cd1c4caad-2'}]}]}}

From the Foursquare lab in the previous module, we know that all the information is in the items key. Before we proceed, let's borrow the get_category_type function from the Foursquare lab.

In [20]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

Now we are ready to clean the json and structure it into a pandas dataframe.Now we are ready to clean the json and structure it into a pandas dataframe.

In [21]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues

              name         categories        lat        lng
0  Brookbanks Park               Park  43.751976 -79.332140
1  GTA Restoration    Fireworks Store  43.753396 -79.333477
2    Variety Store  Food & Drink Shop  43.751974 -79.333114

And how many venues were returned by Foursquare?

In [22]:
print('{} venues were returned by Foursquare.'.format(nearby_venues.shape[0]))

3 venues were returned by Foursquare.

Let's create a function to repeat the same process to all the neighborhoods in Toronto

In [23]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

Now write the code to run the above function on each neighborhood and create a new dataframe called manhattan_venues.

In [25]:
toronto_venues = getNearbyVenues(names=geo['Neighborhood'],
                                   latitudes=geo['Latitude'],
                                   longitudes=geo['Longitude']
                                  )

Parkwoods
Victoria Village
Regent Park / Harbourfront
Lawrence Manor / Lawrence Heights
Queen's Park / Ontario Provincial Government
Islington Avenue
Malvern / Rouge
Don Mills
Parkview Hill / Woodbine Gardens
Garden District, Ryerson
Glencairn
West Deane Park / Princess Gardens / Martin Grove / Islington / Cloverdale
Rouge Hill / Port Union / Highland Creek
Don Mills
Woodbine Heights
St. James Town
Humewood-Cedarvale
Eringate / Bloordale Gardens / Old Burnhamthorpe / Markland Wood
Guildwood / Morningside / West Hill
The Beaches
Berczy Park
Caledonia-Fairbanks
Woburn
Leaside
Central Bay Street
Christie
Cedarbrae
Hillcrest Village
Bathurst Manor / Wilson Heights / Downsview North
Thorncliffe Park
Richmond / Adelaide / King
Dufferin / Dovercourt Village
Scarborough Village
Fairview / Henry Farm / Oriole
Northwood Park / York University
East Toronto
Harbourfront East / Union Station / Toronto Islands
Little Portugal / Trinity
Kennedy Park / Ionview / East Birchmount Park
Bayview Village
Downsview
The Danforth West / Riverdale
Toronto Dominion Centre / Design Exchange
Brockton / Parkdale Village / Exhibition Place
Golden Mile / Clairlea / Oakridge
York Mills / Silver Hills
Downsview
India Bazaar / The Beaches West
Commerce Court / Victoria Hotel
North Park / Maple Leaf Park / Upwood Park
Humber Summit
Cliffside / Cliffcrest / Scarborough Village West
Willowdale / Newtonbrook
Downsview
Studio District
Bedford Park / Lawrence Manor East
Del Ray / Mount Dennis / Keelsdale and Silverthorn
Humberlea / Emery
Birch Cliff / Cliffside West
Willowdale
Downsview
Lawrence Park
Roselawn
Runnymede / The Junction North
Weston
Dorset Park / Wexford Heights / Scarborough Town Centre
York Mills West
Davisville North
Forest Hill North & West
High Park / The Junction South
Westmount
Wexford / Maryvale
Willowdale
North Toronto West
The Annex / North Midtown / Yorkville
Parkdale / Roncesvalles
Canada Post Gateway Processing Centre
Kingsview Village / St. Phillips / Martin Grove Gardens / Richview Gardens
Agincourt
Davisville
University of Toronto / Harbord
Runnymede / Swansea
Clarks Corners / Tam O'Shanter / Sullivan
Moore Park / Summerhill East
Kensington Market / Chinatown / Grange Park
Milliken / Agincourt North / Steeles East / L'Amoreaux East
Summerhill West / Rathnelly / South Hill / Forest Hill SE / Deer Park
CN Tower / King and Spadina / Railway Lands / Harbourfront West / Bathurst  Quay / South Niagara / Island airport
New Toronto / Mimico South / Humber Bay Shores
South Steeles / Silverstone / Humbergate / Jamestown / Mount Olive / Beaumond Heights / Thistletown / Albion Gardens
Steeles West / L'Amoreaux West
Rosedale
Stn A PO Boxes
Alderwood / Long Branch
Northwest
Upper Rouge
St. James Town / Cabbagetown
First Canadian Place / Underground city
The Kingsway / Montgomery Road / Old Mill North
Church and Wellesley
Business reply mail Processing CentrE
Old Mill South / King's Mill Park / Sunnylea / Humber Bay / Mimico NE / The Queensway East / Royal York South East / Kingsway Park South East
Mimico NW / The Queensway West / South of Bloor / Kingsway Park South West / Royal York South West

Let's check the size of the resulting dataframe

In [26]:
print(toronto_venues.shape)
toronto_venues.head()

(2197, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Parkwoods,43.753259,-79.329656,Brookbanks Park,43.751976,-79.332140,Park
1,Parkwoods,43.753259,-79.329656,GTA Restoration,43.753396,-79.333477,Fireworks Store
2,Parkwoods,43.753259,-79.329656,Variety Store,43.751974,-79.333114,Food & Drink Shop
3,Victoria Village,43.725882,-79.315572,Victoria Village Arena,43.723481,-79.315635,Hockey Arena
4,Victoria Village,43.725882,-79.315572,Tim Hortons,43.725517,-79.313103,Coffee Shop

Let's check how many venues were returned for each neighborhood

In [27]:
toronto_venues.groupby('Neighborhood').count().head()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
Agincourt,4,4,4,4,4,4
Alderwood / Long Branch,9,9,9,9,9,9
Bathurst Manor / Wilson Heights / Downsview North,19,19,19,19,19,19
Bayview Village,4,4,4,4,4,4
Bedford Park / Lawrence Manor East,25,25,25,25,25,25

Let's find out how many unique categories can be curated from all the returned venues

In [28]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 271 uniques categories.

Analyze Each Neighborhood

In [29]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot.head()

,Yoga Studio,Accessories Store,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,Aquarium,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Auto Workshop,BBQ Joint,Baby Store,Bagel Shop,Bakery,Bank,Bar,Baseball Field,Baseball Stadium,Basketball Court,Basketball Stadium,Beach,Bed & Breakfast,Beer Bar,Beer Store,Belgian Restaurant,Bike Shop,Bistro,Board Shop,Boat or Ferry,Bookstore,Boutique,Brazilian Restaurant,Breakfast Spot,Brewery,Bridal Shop,Bubble Tea Shop,Building,Burger Joint,Burrito Place,Bus Line,Bus Station,Butcher,Café,Cajun / Creole Restaurant,Camera Store,Candy Store,Caribbean Restaurant,Cheese Shop,Chinese Restaurant,Chocolate Shop,Church,Climbing Gym,Clothing Store,Cocktail Bar,Coffee Shop,College Arts Building,College Auditorium,College Cafeteria,College Gym,College Rec Center,College Stadium,Colombian Restaurant,Comfort Food Restaurant,Comic Shop,Concert Hall,Construction & Landscaping,Convenience Store,Cosmetics Shop,Coworking Space,Creperie,Cuban Restaurant,Cupcake Shop,Curling Ice,Dance Studio,Deli / Bodega,Department Store,Dessert Shop,Dim Sum Restaurant,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Electronics Store,Empanada Restaurant,Ethiopian Restaurant,Event Space,Falafel Restaurant,Farmers Market,Fast Food Restaurant,Field,Filipino Restaurant,Fireworks Store,Fish & Chips Shop,Fish Market,Flea Market,Flower Shop,Food,Food & Drink Shop,Food Court,Food Truck,Fountain,French Restaurant,Fried Chicken Joint,Frozen Yogurt Shop,Fruit & Vegetable Store,Furniture / Home Store,Gaming Cafe,Garden,Garden Center,Gas Station,Gastropub,Gay Bar,General Entertainment,General Travel,German Restaurant,Gift Shop,Gluten-free Restaurant,Golf Course,Gourmet Shop,Greek Restaurant,Grocery Store,Gym,Gym / Fitness Center,Hakka Restaurant,Harbor / Marina,Hardware Store,Health & Beauty Service,Health Food Store,Historic Site,History Museum,Hobby Shop,Hockey Arena,Home Service,Hospital,Hostel,Hotel,Hotel Bar,Housing Development,IT Services,Ice Cream Shop,Indian Restaurant,Indie Movie Theater,Indonesian Restaurant,Indoor Play Area,Intersection,Irish Pub,Italian Restaurant,Japanese Restaurant,Jazz Club,Jewelry Store,Juice Bar,Kids Store,Korean Restaurant,Lake,Latin American Restaurant,Light Rail Station,Lingerie Store,Liquor Store,Lounge,Luggage Store,Mac & Cheese Joint,Market,Martial Arts Dojo,Massage Studio,Medical Center,Mediterranean Restaurant,Men's Store,Mexican Restaurant,Middle Eastern Restaurant,Miscellaneous Shop,Mobile Phone Shop,Modern European Restaurant,Molecular Gastronomy Restaurant,Monument / Landmark,Moroccan Restaurant,Motel,Movie Theater,Museum,Music Venue,Nail Salon,Neighborhood,New American Restaurant,Nightclub,Noodle House,Office,Opera House,Optical Shop,Organic Grocery,Other Great Outdoors,Park,Performing Arts Venue,Pet Store,Pharmacy,Piano Bar,Pizza Place,Plane,Playground,Plaza,Poke Place,Polish Restaurant,Pool,Portuguese Restaurant,Poutine Place,Pub,Ramen Restaurant,Record Shop,Recording Studio,Rental Car Location,Restaurant,River,Roof Deck,Sake Bar,Salad Place,Salon / Barbershop,Sandwich Place,Scenic Lookout,Sculpture Garden,Seafood Restaurant,Shoe Store,Shopping Mall,Skate Park,Skating Rink,Smoke Shop,Snack Place,Soccer Field,South American Restaurant,Spa,Speakeasy,Sporting Goods Shop,Sports Bar,Stadium,Stationery Store,Steakhouse,Strip Club,Supermarket,Supplement Shop,Sushi Restaurant,Swim School,Tailor Shop,Taiwanese Restaurant,Tanning Salon,Tapas Restaurant,Tea Room,Tennis Court,Thai Restaurant,Theater,Theme Restaurant,Thrift / Vintage Store,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Video Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wings Joint,Women's Store
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Parkwoods,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Parkwoods,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Parkwoods,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Victoria Village,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Victoria Village,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

And let's examine the new dataframe size.

In [30]:
toronto_onehot.shape

(2197, 271)

Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [31]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped.head()

,Neighborhood,Yoga Studio,Accessories Store,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,Aquarium,Art Gallery,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Auto Workshop,BBQ Joint,Baby Store,Bagel Shop,Bakery,Bank,Bar,Baseball Field,Baseball Stadium,Basketball Court,Basketball Stadium,Beach,Bed & Breakfast,Beer Bar,Beer Store,Belgian Restaurant,Bike Shop,Bistro,Board Shop,Boat or Ferry,Bookstore,Boutique,Brazilian Restaurant,Breakfast Spot,Brewery,Bridal Shop,Bubble Tea Shop,Building,Burger Joint,Burrito Place,Bus Line,Bus Station,Butcher,Café,Cajun / Creole Restaurant,Camera Store,Candy Store,Caribbean Restaurant,Cheese Shop,Chinese Restaurant,Chocolate Shop,Church,Climbing Gym,Clothing Store,Cocktail Bar,Coffee Shop,College Arts Building,College Auditorium,College Cafeteria,College Gym,College Rec Center,College Stadium,Colombian Restaurant,Comfort Food Restaurant,Comic Shop,Concert Hall,Construction & Landscaping,Convenience Store,Cosmetics Shop,Coworking Space,Creperie,Cuban Restaurant,Cupcake Shop,Curling Ice,Dance Studio,Deli / Bodega,Department Store,Dessert Shop,Dim Sum Restaurant,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Electronics Store,Empanada Restaurant,Ethiopian Restaurant,Event Space,Falafel Restaurant,Farmers Market,Fast Food Restaurant,Field,Filipino Restaurant,Fireworks Store,Fish & Chips Shop,Fish Market,Flea Market,Flower Shop,Food,Food & Drink Shop,Food Court,Food Truck,Fountain,French Restaurant,Fried Chicken Joint,Frozen Yogurt Shop,Fruit & Vegetable Store,Furniture / Home Store,Gaming Cafe,Garden,Garden Center,Gas Station,Gastropub,Gay Bar,General Entertainment,General Travel,German Restaurant,Gift Shop,Gluten-free Restaurant,Golf Course,Gourmet Shop,Greek Restaurant,Grocery Store,Gym,Gym / Fitness Center,Hakka Restaurant,Harbor / Marina,Hardware Store,Health & Beauty Service,Health Food Store,Historic Site,History Museum,Hobby Shop,Hockey Arena,Home Service,Hospital,Hostel,Hotel,Hotel Bar,Housing Development,IT Services,Ice Cream Shop,Indian Restaurant,Indie Movie Theater,Indonesian Restaurant,Indoor Play Area,Intersection,Irish Pub,Italian Restaurant,Japanese Restaurant,Jazz Club,Jewelry Store,Juice Bar,Kids Store,Korean Restaurant,Lake,Latin American Restaurant,Light Rail Station,Lingerie Store,Liquor Store,Lounge,Luggage Store,Mac & Cheese Joint,Market,Martial Arts Dojo,Massage Studio,Medical Center,Mediterranean Restaurant,Men's Store,Mexican Restaurant,Middle Eastern Restaurant,Miscellaneous Shop,Mobile Phone Shop,Modern European Restaurant,Molecular Gastronomy Restaurant,Monument / Landmark,Moroccan Restaurant,Motel,Movie Theater,Museum,Music Venue,Nail Salon,New American Restaurant,Nightclub,Noodle House,Office,Opera House,Optical Shop,Organic Grocery,Other Great Outdoors,Park,Performing Arts Venue,Pet Store,Pharmacy,Piano Bar,Pizza Place,Plane,Playground,Plaza,Poke Place,Polish Restaurant,Pool,Portuguese Restaurant,Poutine Place,Pub,Ramen Restaurant,Record Shop,Recording Studio,Rental Car Location,Restaurant,River,Roof Deck,Sake Bar,Salad Place,Salon / Barbershop,Sandwich Place,Scenic Lookout,Sculpture Garden,Seafood Restaurant,Shoe Store,Shopping Mall,Skate Park,Skating Rink,Smoke Shop,Snack Place,Soccer Field,South American Restaurant,Spa,Speakeasy,Sporting Goods Shop,Sports Bar,Stadium,Stationery Store,Steakhouse,Strip Club,Supermarket,Supplement Shop,Sushi Restaurant,Swim School,Tailor Shop,Taiwanese Restaurant,Tanning Salon,Tapas Restaurant,Tea Room,Tennis Court,Thai Restaurant,Theater,Theme Restaurant,Thrift / Vintage Store,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Video Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wings Joint,Women's Store
0,Agincourt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.25,0.0,0.0,0.00,0.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.250000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Alderwood / Long Branch,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.0,0.0,0.0,0.111111,0.0,0.0,0.111111,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.111111,0.0,0.0,0.0,0.0,0.000000,0.0,0.111111,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Bathurst Manor / Wilson Heights / Downsview North,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.105263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.105263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.052632,0.0,0.0,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.052632,0.052632,0.0,0.0,0.0,0.0,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.052632,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.052632,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.052632,0.0,0.0,0.0,0.0,0.052632,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.052632,0.0,0.052632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Bayview Village,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,0.0,0.0,0.0,0.0,0.0,0.25,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.25,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Bedford Park / Lawrence Manor East,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.04,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.080000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.04,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.04,0.0,0.0,0.0,0.0,0.0,0.08,0.00,0.0,0.0,0.04,0.0,0.0,0.0,0.00,0.0,0.0,0.04,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.040000,0.0,0.080000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.040000,0.0,0.0,0.0,0.0,0.080000,0.0,0.0,0.0,0.0,0.0,0.080000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.040000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Let's confirm the new size

In [32]:
toronto_grouped.shape

(94, 271)

In [33]:
num_top_venues = 5

for hood in toronto_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped[toronto_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')
    
%%hide output

----Agincourt----
                       venue  freq
0                     Lounge  0.25
1               Skating Rink  0.25
2  Latin American Restaurant  0.25
3             Breakfast Spot  0.25
4                Men's Store  0.00


----Alderwood / Long Branch----
            venue  freq
0     Pizza Place  0.22
1        Pharmacy  0.11
2  Sandwich Place  0.11
3    Skating Rink  0.11
4             Gym  0.11


----Bathurst Manor / Wilson Heights / Downsview North----
           venue  freq
0           Bank  0.11
1    Coffee Shop  0.11
2  Shopping Mall  0.05
3     Restaurant  0.05
4    Supermarket  0.05


----Bayview Village----
                 venue  freq
0                 Café  0.25
1                 Bank  0.25
2   Chinese Restaurant  0.25
3  Japanese Restaurant  0.25
4          Yoga Studio  0.00


----Bedford Park / Lawrence Manor East----
                venue  freq
0      Sandwich Place  0.08
1         Pizza Place  0.08
2          Restaurant  0.08
3  Italian Restaurant  0.08
4         Coffee Shop  0.08


----Berczy Park----
          venue  freq
0   Coffee Shop  0.09
1  Cocktail Bar  0.05
2   Cheese Shop  0.04
3    Restaurant  0.04
4        Bakery  0.04


----Birch Cliff / Cliffside West----
                   venue  freq
0        College Stadium  0.25
1                   Café  0.25
2           Skating Rink  0.25
3  General Entertainment  0.25
4            Yoga Studio  0.00


----Brockton / Parkdale Village / Exhibition Place----
            venue  freq
0            Café  0.13
1     Coffee Shop  0.09
2  Breakfast Spot  0.09
3     Yoga Studio  0.04
4    Intersection  0.04


----Business reply mail Processing CentrE----
                  venue  freq
0           Yoga Studio  0.06
1         Auto Workshop  0.06
2            Smoke Shop  0.06
3  Fast Food Restaurant  0.06
4                   Spa  0.06


----CN Tower / King and Spadina / Railway Lands / Harbourfront West / Bathurst  Quay / South Niagara / Island airport----
              venue  freq
0   Airport Service  0.18
1    Airport Lounge  0.12
2  Airport Terminal  0.12
3             Plane  0.06
4   Harbor / Marina  0.06


----Caledonia-Fairbanks----
                        venue  freq
0                        Park  0.50
1               Women's Store  0.25
2                      Market  0.25
3                 Men's Store  0.00
4  Modern European Restaurant  0.00


----Canada Post Gateway Processing Centre----
                      venue  freq
0              Intersection  0.17
1                     Hotel  0.17
2               Coffee Shop  0.17
3                       Gym  0.08
4  Mediterranean Restaurant  0.08


----Cedarbrae----
                  venue  freq
0      Hakka Restaurant  0.12
1    Athletics & Sports  0.12
2   Fried Chicken Joint  0.12
3  Caribbean Restaurant  0.12
4                  Bank  0.12


----Central Bay Street----
                 venue  freq
0          Coffee Shop  0.18
1   Italian Restaurant  0.05
2         Burger Joint  0.04
3      Thai Restaurant  0.04
4  Japanese Restaurant  0.04


----Christie----
           venue  freq
0  Grocery Store  0.22
1           Café  0.17
2           Park  0.11
3    Coffee Shop  0.06
4          Diner  0.06


----Church and Wellesley----
                 venue  freq
0          Coffee Shop  0.06
1  Japanese Restaurant  0.06
2              Gay Bar  0.05
3     Sushi Restaurant  0.04
4           Restaurant  0.04


----Clarks Corners / Tam O'Shanter / Sullivan----
                  venue  freq
0              Pharmacy  0.15
1           Pizza Place  0.15
2  Fast Food Restaurant  0.08
3    Italian Restaurant  0.08
4   Fried Chicken Joint  0.08


----Cliffside / Cliffcrest / Scarborough Village West----
                             venue  freq
0                            Motel   0.5
1              American Restaurant   0.5
2  Molecular Gastronomy Restaurant   0.0
3       Modern European Restaurant   0.0
4                Mobile Phone Shop   0.0


----Commerce Court / Victoria Hotel----
         venue  freq
0  Coffee Shop  0.12
1   Restaurant  0.07
2         Café  0.07
3        Hotel  0.05
4          Gym  0.04


----Davisville----
            venue  freq
0     Pizza Place  0.11
1  Sandwich Place  0.09
2    Dessert Shop  0.09
3            Café  0.06
4             Gym  0.06


----Davisville North----
               venue  freq
0               Park  0.11
1  Food & Drink Shop  0.11
2     Sandwich Place  0.11
3   Asian Restaurant  0.11
4   Department Store  0.11


----Del Ray / Mount Dennis / Keelsdale and Silverthorn----
            venue  freq
0  Discount Store  0.25
1      Restaurant  0.25
2  Sandwich Place  0.25
3     Coffee Shop  0.25
4  Massage Studio  0.00


----Don Mills----
                 venue  freq
0          Coffee Shop  0.08
1           Restaurant  0.08
2           Beer Store  0.08
3  Japanese Restaurant  0.08
4                  Gym  0.08


----Dorset Park / Wexford Heights / Scarborough Town Centre----
                   venue  freq
0      Indian Restaurant  0.33
1              Pet Store  0.17
2  Vietnamese Restaurant  0.17
3                Brewery  0.17
4     Chinese Restaurant  0.17


----Downsview----
                venue  freq
0       Grocery Store  0.19
1                Park  0.12
2        Home Service  0.06
3  Athletics & Sports  0.06
4                Bank  0.06


----Dufferin / Dovercourt Village----
      venue  freq
0    Bakery  0.11
1  Pharmacy  0.11
2      Pool  0.06
3      Park  0.06
4      Café  0.06


----East Toronto----
                        venue  freq
0                        Park  0.67
1           Convenience Store  0.33
2                 Yoga Studio  0.00
3                 Men's Store  0.00
4  Modern European Restaurant  0.00


----Eringate / Bloordale Gardens / Old Burnhamthorpe / Markland Wood----
            venue  freq
0     Pizza Place  0.14
1  Cosmetics Shop  0.14
2      Beer Store  0.14
3    Liquor Store  0.14
4     Coffee Shop  0.14


----Fairview / Henry Farm / Oriole----
                  venue  freq
0        Clothing Store  0.13
1           Coffee Shop  0.07
2  Fast Food Restaurant  0.06
3         Women's Store  0.04
4   Japanese Restaurant  0.04


----First Canadian Place / Underground city----
                 venue  freq
0          Coffee Shop  0.12
1                 Café  0.07
2           Restaurant  0.06
3  Japanese Restaurant  0.03
4            Gastropub  0.03


----Forest Hill North & West----
                venue  freq
0               Trail  0.25
1    Sushi Restaurant  0.25
2  Mexican Restaurant  0.25
3       Jewelry Store  0.25
4         Yoga Studio  0.00


----Garden District, Ryerson----
                       venue  freq
0             Clothing Store  0.08
1                Coffee Shop  0.08
2        Japanese Restaurant  0.03
3                       Café  0.03
4  Middle Eastern Restaurant  0.03


----Glencairn----
                 venue  freq
0                 Park  0.25
1          Pizza Place  0.25
2                  Pub  0.25
3  Japanese Restaurant  0.25
4   Mexican Restaurant  0.00


----Golden Mile / Clairlea / Oakridge----
            venue  freq
0          Bakery  0.22
1        Bus Line  0.22
2    Soccer Field  0.11
3  Ice Cream Shop  0.11
4     Bus Station  0.11


----Guildwood / Morningside / West Hill----
                 venue  freq
0   Mexican Restaurant  0.14
1       Medical Center  0.14
2  Rental Car Location  0.14
3                 Bank  0.14
4    Electronics Store  0.14


----Harbourfront East / Union Station / Toronto Islands----
                venue  freq
0         Coffee Shop  0.12
1            Aquarium  0.05
2               Hotel  0.04
3                Café  0.04
4  Italian Restaurant  0.04


----High Park / The Junction South----
                venue  freq
0     Thai Restaurant  0.08
1  Mexican Restaurant  0.08
2                Café  0.08
3                 Bar  0.08
4           Speakeasy  0.04


----Hillcrest Village----
                      venue  freq
0      Fast Food Restaurant   0.2
1                      Pool   0.2
2                   Dog Run   0.2
3               Golf Course   0.2
4  Mediterranean Restaurant   0.2


----Humber Summit----
                 venue  freq
0  Empanada Restaurant   1.0
1          Yoga Studio   0.0
2  Monument / Landmark   0.0
3   Mac & Cheese Joint   0.0
4               Market   0.0


----Humberlea / Emery----
                             venue  freq
0                   Baseball Field   1.0
1                      Yoga Studio   0.0
2               Mexican Restaurant   0.0
3  Molecular Gastronomy Restaurant   0.0
4       Modern European Restaurant   0.0


----Humewood-Cedarvale----
          venue  freq
0         Field  0.25
1    Playground  0.25
2  Hockey Arena  0.25
3         Trail  0.25

4   Yoga Studio  0.00


----India Bazaar / The Beaches West----
               venue  freq
0               Park  0.11
1  Fish & Chips Shop  0.05
2        Coffee Shop  0.05
3      Burrito Place  0.05
4         Board Shop  0.05


----Kennedy Park / Ionview / East Birchmount Park----
               venue  freq
0  Convenience Store  0.25
1        Bus Station  0.25
2   Department Store  0.25
3        Coffee Shop  0.25
4        Yoga Studio  0.00


----Kensington Market / Chinatown / Grange Park----
                   venue  freq
0                   Café  0.07
1  Vietnamese Restaurant  0.05
2            Coffee Shop  0.05
3                    Bar  0.05
4    Dumpling Restaurant  0.04


----Kingsview Village / St. Phillips / Martin Grove Gardens / Richview Gardens----
                      venue  freq
0                      Park  0.25
1         Mobile Phone Shop  0.25
2               Pizza Place  0.25
3            Sandwich Place  0.25
4  Mediterranean Restaurant  0.00


----Lawrence Manor / Lawrence Heights----
                    venue  freq
0          Clothing Store  0.42
1  Furniture / Home Store  0.08
2             Coffee Shop  0.08
3       Accessories Store  0.08
4                Boutique  0.08


----Lawrence Park----
         venue  freq
0         Park  0.33
1  Swim School  0.33
2     Bus Line  0.33
3  Yoga Studio  0.00
4  Men's Store  0.00


----Leaside----
                 venue  freq
0          Coffee Shop  0.09
1  Sporting Goods Shop  0.09
2                 Bank  0.06
3         Burger Joint  0.06
4     Sushi Restaurant  0.06


----Little Portugal / Trinity----
                   venue  freq
0                    Bar  0.12
1            Coffee Shop  0.06
2       Asian Restaurant  0.06
3  Vietnamese Restaurant  0.04
4            Pizza Place  0.04


----Malvern / Rouge----
                  venue  freq
0  Fast Food Restaurant   1.0
1   Monument / Landmark   0.0
2         Luggage Store   0.0
3    Mac & Cheese Joint   0.0
4                Market   0.0


----Milliken / Agincourt North / Steeles East / L'Amoreaux East----
                        venue  freq
0                        Park   0.5
1                  Playground   0.5
2                 Yoga Studio   0.0
3    Mediterranean Restaurant   0.0
4  Modern European Restaurant   0.0


----Mimico NW / The Queensway West / South of Bloor / Kingsway Park South West / Royal York South West----
                  venue  freq
0           Flower Shop  0.07
1        Discount Store  0.07
2  Fast Food Restaurant  0.07
3          Burger Joint  0.07
4     Convenience Store  0.07


----Moore Park / Summerhill East----
          venue  freq
0  Tennis Court  0.33
1    Playground  0.33
2    Restaurant  0.33
3   Yoga Studio  0.00
4   Men's Store  0.00


----New Toronto / Mimico South / Humber Bay Shores----
                  venue  freq
0  Fast Food Restaurant   0.1
1          Liquor Store   0.1
2                Bakery   0.1
3   Fried Chicken Joint   0.1
4                  Café   0.1


----North Park / Maple Leaf Park / Upwood Park----
                        venue  freq
0                      Bakery  0.25
1  Construction & Landscaping  0.25
2                        Park  0.25
3            Basketball Court  0.25
4          Mexican Restaurant  0.00


----North Toronto West----
                 venue  freq
0       Clothing Store  0.19
1          Coffee Shop  0.10
2          Yoga Studio  0.05
3  Sporting Goods Shop  0.05
4         Dessert Shop  0.05


----Northwest----
                 venue  freq
0  Rental Car Location  0.33
1                  Bar  0.33
2            Drugstore  0.33
3          Yoga Studio  0.00
4  Monument / Landmark  0.00


----Northwood Park / York University----
                  venue  freq
0  Caribbean Restaurant  0.25
1        Massage Studio  0.25
2                   Bar  0.25
3           Coffee Shop  0.25
4           Yoga Studio  0.00


----Old Mill South / King's Mill Park / Sunnylea / Humber Bay / Mimico NE / The Queensway East / Royal York South East / Kingsway Park South East----
                             venue  freq
0                   Baseball Field   1.0
1                      Yoga Studio   0.0
2               Mexican Restaurant   0.0
3  Molecular Gastronomy Restaurant   0.0
4       Modern European Restaurant   0.0


----Parkdale / Roncesvalles----
                         venue  freq
0                    Gift Shop  0.15
1                    Bookstore  0.08
2                  Coffee Shop  0.08
3  Eastern European Restaurant  0.08
4                          Bar  0.08


----Parkview Hill / Woodbine Gardens----
                  venue  freq
0           Pizza Place  0.15
1              Pharmacy  0.08
2    Athletics & Sports  0.08
3  Fast Food Restaurant  0.08
4             Pet Store  0.08


----Parkwoods----
               venue  freq
0  Food & Drink Shop  0.33
1               Park  0.33
2    Fireworks Store  0.33
3     Medical Center  0.00
4  Mobile Phone Shop  0.00


----Queen's Park / Ontario Provincial Government----
                venue  freq
0         Coffee Shop  0.24
1         Yoga Studio  0.03
2  Italian Restaurant  0.03
3        Burger Joint  0.03
4                Café  0.03


----Regent Park / Harbourfront----
         venue  freq
0  Coffee Shop  0.18
1       Bakery  0.07
2          Pub  0.07
3         Park  0.07
4         Café  0.04


----Richmond / Adelaide / King----
             venue  freq
0             Café  0.06
1      Coffee Shop  0.06
2       Restaurant  0.06
3              Bar  0.03
4  Thai Restaurant  0.03


----Rosedale----
                        venue  freq
0                        Park  0.50
1                       Trail  0.25
2                  Playground  0.25
3  Modern European Restaurant  0.00
4           Mobile Phone Shop  0.00


----Roselawn----
                             venue  freq
0                           Garden   1.0
1                      Men's Store   0.0
2  Molecular Gastronomy Restaurant   0.0
3       Modern European Restaurant   0.0
4                Mobile Phone Shop   0.0


----Rouge Hill / Port Union / Highland Creek----
                             venue  freq
0                              Bar   1.0
1                      Yoga Studio   0.0
2               Mexican Restaurant   0.0
3  Molecular Gastronomy Restaurant   0.0
4       Modern European Restaurant   0.0


----Runnymede / Swansea----
              venue  freq
0       Pizza Place  0.07
1       Coffee Shop  0.07
2              Café  0.07
3  Sushi Restaurant  0.04
4               Pub  0.04


----Runnymede / The Junction North----
               venue  freq
0        Pizza Place  0.25
1  Convenience Store  0.25
2            Brewery  0.25
3           Bus Line  0.25
4        Yoga Studio  0.00


----Scarborough Village----
                             venue  freq
0                       Playground   0.5
1                Convenience Store   0.5
2                      Yoga Studio   0.0
3                      Men's Store   0.0
4  Molecular Gastronomy Restaurant   0.0


----South Steeles / Silverstone / Humbergate / Jamestown / Mount Olive / Beaumond Heights / Thistletown / Albion Gardens----
                  venue  freq
0           Pizza Place  0.17
1         Grocery Store  0.17
2              Pharmacy  0.08
3  Fast Food Restaurant  0.08
4          Liquor Store  0.08


----St. James Town----
          venue  freq
0   Coffee Shop  0.08
1          Café  0.05
2    Restaurant  0.04
3     Gastropub  0.03
4  Cocktail Bar  0.03


----St. James Town / Cabbagetown----
                venue  freq
0         Pizza Place  0.07
1         Coffee Shop  0.07
2                Café  0.05
3              Bakery  0.05
4  Italian Restaurant  0.05


----Steeles West / L'Amoreaux West----
                  venue  freq
0    Chinese Restaurant  0.13
1  Fast Food Restaurant  0.13
2     Indian Restaurant  0.07
3                  Bank  0.07
4        Breakfast Spot  0.07


----Stn A PO Boxes----
                venue  freq
0         Coffee Shop  0.13
1          Restaurant  0.04
2  Seafood Restaurant  0.04
3                Café  0.04
4               Hotel  0.03


----Studio District----
         venue  freq
0         Café  0.10
1  Coffee Shop  0.07
2    Gastropub  0.05
3       Bakery  0.05
4      Brewery  0.05


----Summerhill West / Rathnelly / South Hill / Forest Hill SE / Deer Park----

                 venue  freq
0                  Pub  0.13
1          Coffee Shop  0.13
2          Pizza Place  0.07
3  American Restaurant  0.07
4                 Bank  0.07


----The Annex / North Midtown / Yorkville----
               venue  freq
0               Café  0.13
1        Coffee Shop  0.09
2     Sandwich Place  0.09
3     History Museum  0.04
4  Indian Restaurant  0.04


----The Beaches----
                        venue  freq
0                        Park   0.2
1                       Trail   0.2
2           Health Food Store   0.2
3                         Pub   0.2
4  Modern European Restaurant   0.0


----The Danforth West / Riverdale----
                    venue  freq
0        Greek Restaurant  0.19
1             Coffee Shop  0.10
2      Italian Restaurant  0.07
3  Furniture / Home Store  0.05
4               Bookstore  0.05


----The Kingsway / Montgomery Road / Old Mill North----
                        venue  freq
0                        Park  0.33
1                        Pool  0.33
2                       River  0.33
3  Modern European Restaurant  0.00
4           Mobile Phone Shop  0.00


----Thorncliffe Park----
               venue  freq
0  Indian Restaurant  0.10
1        Yoga Studio  0.05
2           Pharmacy  0.05
3        Pizza Place  0.05
4        Coffee Shop  0.05


----Toronto Dominion Centre / Design Exchange----
                 venue  freq
0          Coffee Shop  0.15
1                 Café  0.08
2                Hotel  0.07
3           Restaurant  0.06
4  American Restaurant  0.03


----University of Toronto / Harbord----
        venue  freq
0        Café  0.17
1  Restaurant  0.06
2   Bookstore  0.06
3         Bar  0.06
4      Bakery  0.06


----Victoria Village----
                   venue  freq
0            Coffee Shop   0.2
1            Pizza Place   0.2
2           Hockey Arena   0.2
3           Intersection   0.2
4  Portuguese Restaurant   0.2


----Westmount----
                       venue  freq
0                Pizza Place  0.25
1                Coffee Shop  0.12
2  Middle Eastern Restaurant  0.12
3         Chinese Restaurant  0.12
4             Sandwich Place  0.12


----Weston----
                             venue  freq
0                Convenience Store   1.0
1                      Yoga Studio   0.0
2                      Men's Store   0.0
3  Molecular Gastronomy Restaurant   0.0
4       Modern European Restaurant   0.0


----Wexford / Maryvale----
                       venue  freq
0                     Bakery  0.25
1                 Smoke Shop  0.25
2             Breakfast Spot  0.25
3  Middle Eastern Restaurant  0.25
4                Yoga Studio  0.00


----Willowdale----
              venue  freq
0       Pizza Place  0.08
1       Coffee Shop  0.08
2  Ramen Restaurant  0.08
3    Discount Store  0.05
4              Café  0.05


----Willowdale / Newtonbrook----
                        venue  freq
0                   Piano Bar   1.0
1                 Yoga Studio   0.0
2    Mediterranean Restaurant   0.0
3  Modern European Restaurant   0.0
4           Mobile Phone Shop   0.0


----Woburn----
                             venue  freq
0                      Coffee Shop  0.67
1                Korean Restaurant  0.33
2                      Yoga Studio  0.00
3               Mexican Restaurant  0.00
4  Molecular Gastronomy Restaurant  0.00


----Woodbine Heights----
                venue  freq
0        Skating Rink   0.2
1                Park   0.1
2         Video Store   0.1
3               Diner   0.1
4  Athletics & Sports   0.1


----York Mills West----
               venue  freq
0               Park   0.4
1               Bank   0.2
2  Convenience Store   0.2
3                Bar   0.2
4        Yoga Studio   0.0

UsageError: Line magic function `%%hide` not found.

Let's put that into a pandas dataframe First, let's write a function to sort the venues in descending order.

In [34]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

Now let's create the new dataframe and display the top 10 venues for each neighborhood.

In [51]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Agincourt,Latin American Restaurant,Skating Rink,Lounge,Breakfast Spot,Women's Store,Drugstore,Distribution Center,Dog Run,Doner Restaurant,Donut Shop
1,Alderwood / Long Branch,Pizza Place,Pub,Gym,Skating Rink,Coffee Shop,Pharmacy,Pool,Sandwich Place,Distribution Center,Dessert Shop
2,Bathurst Manor / Wilson Heights / Downsview North,Coffee Shop,Bank,Frozen Yogurt Shop,Shopping Mall,Sandwich Place,Bridal Shop,Restaurant,Diner,Deli / Bodega,Supermarket
3,Bayview Village,Japanese Restaurant,Chinese Restaurant,Bank,Café,Empanada Restaurant,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Drugstore,Diner
4,Bedford Park / Lawrence Manor East,Sandwich Place,Pizza Place,Coffee Shop,Restaurant,Italian Restaurant,Comfort Food Restaurant,Café,Indian Restaurant,Butcher,Sushi Restaurant

Cluster Neighborhoods

Run k-means to cluster the neighborhood into 5 clusters.

In [52]:
# set number of clusters
kclusters = 3

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

In [53]:
# add clustering labels
neighborhoods_venues_sorted.insert(0, 'cluster labels', kmeans.labels_)

toronto_merged = geo

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

toronto_merged.head() # check the last columns!

,Postal code,Borough,Neighborhood,Latitude,Longitude,cluster labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,M3A,North York,Parkwoods,43.753259,-79.329656,2.0,Park,Fireworks Store,Food & Drink Shop,Donut Shop,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Drugstore
1,M4A,North York,Victoria Village,43.725882,-79.315572,0.0,Hockey Arena,Intersection,Pizza Place,Coffee Shop,Portuguese Restaurant,Women's Store,Diner,Discount Store,Distribution Center,Dog Run
2,M5A,Downtown Toronto,Regent Park / Harbourfront,43.654260,-79.360636,0.0,Coffee Shop,Pub,Park,Bakery,Mexican Restaurant,Breakfast Spot,Café,Ice Cream Shop,Electronics Store,Hotel
3,M6A,North York,Lawrence Manor / Lawrence Heights,43.718518,-79.464763,0.0,Clothing Store,Furniture / Home Store,Coffee Shop,Boutique,Miscellaneous Shop,Event Space,Accessories Store,Vietnamese Restaurant,Convenience Store,Concert Hall
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government,43.662301,-79.389494,0.0,Coffee Shop,Yoga Studio,Café,Beer Bar,Italian Restaurant,Juice Bar,Boutique,Burger Joint,Burrito Place,Restaurant

Finally, let's visualize the resulting clusters

In [54]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['cluster labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        fill=True,
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

#### Examine Clusters
We can examine each cluster and determine the discriminating venue categories that distinguish each cluster.

### Cluster 1

In [62]:
toronto_merged.loc[toronto_merged['cluster labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,cluster labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,North York,0.0,Hockey Arena,Intersection,Pizza Place,Coffee Shop,Portuguese Restaurant,Women's Store,Diner,Discount Store,Distribution Center,Dog Run
2,Downtown Toronto,0.0,Coffee Shop,Pub,Park,Bakery,Mexican Restaurant,Breakfast Spot,Café,Ice Cream Shop,Electronics Store,Hotel
3,North York,0.0,Clothing Store,Furniture / Home Store,Coffee Shop,Boutique,Miscellaneous Shop,Event Space,Accessories Store,Vietnamese Restaurant,Convenience Store,Concert Hall
4,Downtown Toronto,0.0,Coffee Shop,Yoga Studio,Café,Beer Bar,Italian Restaurant,Juice Bar,Boutique,Burger Joint,Burrito Place,Restaurant
6,Scarborough,0.0,Fast Food Restaurant,Drugstore,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Women's Store,Dim Sum Restaurant
7,North York,0.0,Restaurant,Gym,Coffee Shop,Japanese Restaurant,Beer Store,Gym / Fitness Center,Sporting Goods Shop,Bike Shop,Sandwich Place,Discount Store
8,East York,0.0,Pizza Place,Gym / Fitness Center,Gastropub,Fast Food Restaurant,Bus Line,Intersection,Café,Bank,Athletics & Sports,Breakfast Spot
9,Downtown Toronto,0.0,Coffee Shop,Clothing Store,Café,Japanese Restaurant,Bubble Tea Shop,Middle Eastern Restaurant,Cosmetics Shop,Lingerie Store,Ramen Restaurant,Bookstore
10,North York,0.0,Park,Pizza Place,Pub,Japanese Restaurant,Eastern European Restaurant,Dumpling Restaurant,Electronics Store,Drugstore,Donut Shop,Department Store
12,Scarborough,0.0,Bar,Women's Store,Drugstore,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant,Fast Food Restaurant
13,North York,0.0,Restaurant,Gym,Coffee Shop,Japanese Restaurant,Beer Store,Gym / Fitness Center,Sporting Goods Shop,Bike Shop,Sandwich Place,Discount Store
14,East York,0.0,Skating Rink,Park,Video Store,Pharmacy,Beer Store,Athletics & Sports,Cosmetics Shop,Diner,Curling Ice,Women's Store
15,Downtown Toronto,0.0,Coffee Shop,Café,Restaurant,American Restaurant,Italian Restaurant,Diner,Cocktail Bar,Bakery,Japanese Restaurant,Cosmetics Shop
16,York,0.0,Trail,Hockey Arena,Field,Playground,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop
17,Etobicoke,0.0,Park,Pizza Place,Beer Store,Café,Cosmetics Shop,Coffee Shop,Liquor Store,Convenience Store,Construction & Landscaping,Ethiopian Restaurant
18,Scarborough,0.0,Rental Car Location,Medical Center,Mexican Restaurant,Breakfast Spot,Electronics Store,Bank,Intersection,Distribution Center,Dog Run,Doner Restaurant
19,East Toronto,0.0,Park,Health Food Store,Pub,Trail,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Empanada Restaurant,Drugstore,Department Store
20,Downtown Toronto,0.0,Coffee Shop,Cocktail Bar,Café,Cheese Shop,Beer Bar,Seafood Restaurant,Farmers Market,Bakery,Restaurant,Liquor Store
22,Scarborough,0.0,Coffee Shop,Korean Restaurant,Women's Store,Drugstore,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Eastern European Restaurant
23,East York,0.0,Coffee Shop,Sporting Goods Shop,Burger Joint,Furniture / Home Store,Sushi Restaurant,Bank,Liquor Store,Dessert Shop,Restaurant,Electronics Store
24,Downtown Toronto,0.0,Coffee Shop,Italian Restaurant,Sandwich Place,Thai Restaurant,Japanese Restaurant,Burger Joint,Café,Salad Place,Spa,Ice Cream Shop
25,Downtown Toronto,0.0,Grocery Store,Café,Park,Baby Store,Coffee Shop,Restaurant,Athletics & Sports,Italian Restaurant,Diner,Gas Station
26,Scarborough,0.0,Caribbean Restaurant,Gas Station,Bank,Fried Chicken Joint,Athletics & Sports,Thai Restaurant,Bakery,Hakka Restaurant,Eastern European Restaurant,Dumpling Restaurant
27,North York,0.0,Fast Food Restaurant,Golf Course,Dog Run,Mediterranean Restaurant,Pool,Women's Store,Donut Shop,Discount Store,Distribution Center,Doner Restaurant
28,North York,0.0,Coffee Shop,Bank,Frozen Yogurt Shop,Shopping Mall,Sandwich Place,Bridal Shop,Restaurant,Diner,Deli / Bodega,Supermarket
29,East York,0.0,Indian Restaurant,Gym / Fitness Center,Gym,Pizza Place,Pharmacy,Park,Liquor Store,Housing Development,Grocery Store,Supermarket
30,Downtown Toronto,0.0,Coffee Shop,Café,Restaurant,Bar,Thai Restaurant,Gym,Bakery,Clothing Store,Hotel,Gastropub
31,West Toronto,0.0,Pharmacy,Bakery,Gym / Fitness Center,Middle Eastern Restaurant,Brewery,Grocery Store,Music Venue,Supermarket,Bar,Smoke Shop
32,Scarborough,0.0,Playground,Convenience Store,Women's Store,Drugstore,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop
33,North York,0.0,Clothing Store,Coffee Shop,Fast Food Restaurant,Women's Store,Japanese Restaurant,Restaurant,Tea Room,Juice Bar,Jewelry Store,Bank
34,North York,0.0,Caribbean Restaurant,Bar,Coffee Shop,Massage Studio,Women's Store,Drugstore,Distribution Center,Dog Run,Doner Restaurant,Donut Shop
36,Downtown Toronto,0.0,Coffee Shop,Aquarium,Italian Restaurant,Café,Hotel,Fried Chicken Joint,Scenic Lookout,Sporting Goods Shop,Brewery,Restaurant
37,West Toronto,0.0,Bar,Coffee Shop,Asian Restaurant,Vietnamese Restaurant,Restaurant,Pizza Place,Café,Men's Store,Yoga Studio,Beer Store
38,Scarborough,0.0,Bus Station,Department Store,Convenience Store,Coffee Shop,Dumpling Restaurant,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Drugstore
39,North York,0.0,Japanese Restaurant,Chinese Restaurant,Bank,Café,Empanada Restaurant,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Drugstore,Diner
40,North York,0.0,Grocery Store,Park,Gym / Fitness Center,Food Truck,Discount Store,Bank,Hotel,Home Service,Athletics & Sports,Baseball Field
41,East Toronto,0.0,Greek Restaurant,Coffee Shop,Italian Restaurant,Ice Cream Shop,Bookstore,Furniture / Home Store,Spa,Diner,Indian Restaurant,Caribbean Restaurant
42,Downtown Toronto,0.0,Coffee Shop,Café,Hotel,Restaurant,Gastropub,Seafood Restaurant,Bar,American Restaurant,Deli / Bodega,Tea Room
43,West Toronto,0.0,Café,Coffee Shop,Breakfast Spot,Yoga Studio,Bakery,Convenience Store,Performing Arts Venue,Pet Store,Climbing Gym,Restaurant
44,Scarborough,0.0,Bakery,Bus Line,Park,Soccer Field,Bus Station,Intersection,Ice Cream Shop,Women's Store,Doner Restaurant,Distribution Center
46,North York,0.0,Grocery Store,Park,Gym / Fitness Center,Food Truck,Discount Store,Bank,Hotel,Home Service,Athletics & Sports,Baseball Field
47,East Toronto,0.0,Park,Brewery,Burrito Place,Pub,Sushi Restaurant,Steakhouse,Fish & Chips Shop,Restaurant,Italian Restaurant,Fast Food Restaurant
48,Downtown Toronto,0.0,Coffee Shop,Restaurant,Café,Hotel,American Restaurant,Gym,Seafood Restaurant,Japanese Restaurant,Gastropub,Italian Restaurant
49,North York,0.0,Park,Basketball Court,Bakery,Construction & Landscaping,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant
50,North York,0.0,Empanada Restaurant,Women's Store,Dim Sum Restaurant,Falafel Restaurant,Event Space,Ethiopian Restaurant,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Drugstore
51,Scarborough,0.0,Motel,American Restaurant,Women's Store,Dessert Shop,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop
52,North York,0.0,Piano Bar,Women's Store,Drugstore,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant
53,North York,0.0,Grocery Store,Park,Gym / Fitness Center,Food Truck,Discount Store,Bank,Hotel,Home Service,Athletics & Sports,Baseball Field
54,East Toronto,0.0,Café,Coffee Shop,American Restaurant,Bakery,Brewery,Gastropub,Gym / Fitness Center,Fish Market,Sandwich Place,Pet Store
55,North York,0.0,Sandwich Place,Pizza Place,Coffee Shop,Restaurant,Italian Restaurant,Comfort Food Restaurant,Café,Indian Restaurant,Butcher,Sushi Restaurant
56,York,0.0,Restaurant,Discount Store,Coffee Shop,Sandwich Place,Donut Shop,Diner,Distribution Center,Dog Run,Doner Restaurant,Women's Store
58,Scarborough,0.0,College Stadium,Skating Rink,Café,General Entertainment,Ethiopian Restaurant,Empanada Restaurant,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Event Space
59,North York,0.0,Ramen Restaurant,Pizza Place,Coffee Shop,Café,Restaurant,Sandwich Place,Discount Store,Grocery Store,Steakhouse,Hotel
60,North York,0.0,Grocery Store,Park,Gym / Fitness Center,Food Truck,Discount Store,Bank,Hotel,Home Service,Athletics & Sports,Baseball Field
62,Central Toronto,0.0,Garden,Women's Store,Drugstore,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant,Dim Sum Restaurant
63,York,0.0,Bus Line,Pizza Place,Convenience Store,Brewery,Women's Store,Donut Shop,Discount Store,Distribution Center,Dog Run,Doner Restaurant
64,York,0.0,Convenience Store,Women's Store,Dumpling Restaurant,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Drugstore,Eastern European Restaurant
65,Scarborough,0.0,Indian Restaurant,Pet Store,Vietnamese Restaurant,Chinese Restaurant,Brewery,Women's Store,Doner Restaurant,Diner,Discount Store,Distribution Center
67,Central Toronto,0.0,Gym,Asian Restaurant,Convenience Store,Department Store,Sandwich Place,Breakfast Spot,Food & Drink Shop,Hotel,Park,General Entertainment
68,Central Toronto,0.0,Trail,Mexican Restaurant,Sushi Restaurant,Jewelry Store,Drugstore,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Women's Store
69,West Toronto,0.0,Bar,Mexican Restaurant,Thai Restaurant,Café,Speakeasy,Bookstore,Cajun / Creole Restaurant,Music Venue,Park,Bakery
70,Etobicoke,0.0,Pizza Place,Middle Eastern Restaurant,Discount Store,Intersection,Coffee Shop,Chinese Restaurant,Sandwich Place,Women's Store,Doner Restaurant,Distribution Center
71,Scarborough,0.0,Smoke Shop,Breakfast Spot,Bakery,Middle Eastern Restaurant,Ethiopian Restaurant,Empanada Restaurant,Event Space,Electronics Store,Discount Store,Dumpling Restaurant
72,North York,0.0,Ramen Restaurant,Pizza Place,Coffee Shop,Café,Restaurant,Sandwich Place,Discount Store,Grocery Store,Steakhouse,Hotel
73,Central Toronto,0.0,Clothing Store,Coffee Shop,Yoga Studio,Sporting Goods Shop,Gift Shop,Fast Food Restaurant,Diner,Dessert Shop,Mexican Restaurant,Chinese Restaurant
74,Central Toronto,0.0,Café,Sandwich Place,Coffee Shop,Burger Joint,Pharmacy,Pub,Middle Eastern Restaurant,BBQ Joint,Pizza Place,History Museum
75,West Toronto,0.0,Gift Shop,Cuban Restaurant,Italian Restaurant,Bar,Breakfast Spot,Bookstore,Dessert Shop,Eastern European Restaurant,Coffee Shop,Dog Run
76,Mississauga,0.0,Hotel,Intersection,Coffee Shop,Gym,Sandwich Place,Mediterranean Restaurant,Burrito Place,Fried Chicken Joint,American Restaurant,Drugstore
77,Etobicoke,0.0,Park,Pizza Place,Sandwich Place,Mobile Phone Shop,Eastern European Restaurant,Dumpling Restaurant,Electronics Store,Drugstore,Donut Shop,Department Store
78,Scarborough,0.0,Latin American Restaurant,Skating Rink,Lounge,Breakfast Spot,Women's Store,Drugstore,Distribution Center,Dog Run,Doner Restaurant,Donut Shop
79,Central Toronto,0.0,Pizza Place,Dessert Shop,Sandwich Place,Coffee Shop,Italian Restaurant,Café,Sushi Restaurant,Gym,Restaurant,Indian Restaurant
80,Downtown Toronto,0.0,Café,Restaurant,Bar,Japanese Restaurant,Bookstore,Bakery,Chinese Restaurant,Dessert Shop,College Arts Building,Pub
81,West Toronto,0.0,Coffee Shop,Pizza Place,Café,Sushi Restaurant,Pub,Italian Restaurant,Yoga Studio,Falafel Restaurant,Food,IT Services
82,Scarborough,0.0,Pharmacy,Pizza Place,Bank,Italian Restaurant,Noodle House,Fast Food Restaurant,Shopping Mall,Gas Station,Fried Chicken Joint,Chinese Restaurant
83,Central Toronto,0.0,Restaurant,Tennis Court,Playground,Doner Restaurant,Dim Sum Restaurant,Diner,Discount Store,Distribution Center,Dog Run,Women's Store
84,Downtown Toronto,0.0,Café,Coffee Shop,Vietnamese Restaurant,Bar,Mexican Restaurant,Vegetarian / Vegan Restaurant,Dumpling Restaurant,Farmers Market,Chinese Restaurant,Dessert Shop
86,Central Toronto,0.0,Coffee Shop,Pub,Light Rail Station,Restaurant,Supermarket,Bank,Fried Chicken Joint,Sports Bar,Sushi Restaurant,Pizza Place
87,Downtown Toronto,0.0,Airport Service,Airport Lounge,Airport Terminal,Rental Car Location,Sculpture Garden,Boutique,Harbor / Marina,Boat or Ferry,Airport Gate,Airport Food Court
88,Etobicoke,0.0,Gym,American Restaurant,Fast Food Restaurant,Restaurant,Café,Bakery,Fried Chicken Joint,Liquor Store,Pizza Place,Pharmacy
89,Etobicoke,0.0,Grocery Store,Pizza Place,Fast Food Restaurant,Beer Store,Sandwich Place,Japanese Restaurant,Discount Store,Fried Chicken Joint,Liquor Store,Pharmacy
90,Scarborough,0.0,Chinese Restaurant,Fast Food Restaurant,Grocery Store,Bubble Tea Shop,Burger Joint,Indian Restaurant,Coffee Shop,Pizza Place,Thrift / Vintage Store,Pharmacy
92,Downtown Toronto,0.0,Coffee Shop,Seafood Restaurant,Restaurant,Café,Cocktail Bar,Beer Bar,Hotel,Japanese Restaurant,Art Gallery,Cheese Shop
93,Etobicoke,0.0,Pizza Place,Pub,Gym,Skating Rink,Coffee Shop,Pharmacy,Pool,Sandwich Place,Distribution Center,Dessert Shop
94,Etobicoke,0.0,Rental Car Location,Bar,Drugstore,Ethiopian Restaurant,Empanada Restaurant,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Farmers Market,Donut Shop
96,Downtown Toronto,0.0,Coffee Shop,Pizza Place,Italian Restaurant,Café,Bakery,Restaurant,Pub,Indian Restaurant,Snack Place,Japanese Restaurant
97,Downtown Toronto,0.0,Coffee Shop,Café,Restaurant,Gastropub,Steakhouse,Seafood Restaurant,Asian Restaurant,Gym,Hotel,Japanese Restaurant
99,Downtown Toronto,0.0,Coffee Shop,Japanese Restaurant,Gay Bar,Sushi Restaurant,Restaurant,Yoga Studio,Men's Store,Café,Burger Joint,Pub
100,East Toronto,0.0,Yoga Studio,Auto Workshop,Comic Shop,Pizza Place,Recording Studio,Restaurant,Burrito Place,Brewery,Light Rail Station,Skate Park
102,Etobicoke,0.0,Grocery Store,Kids Store,Discount Store,Burrito Place,Flower Shop,Burger Joint,Supplement Shop,Sandwich Place,Bakery,Convenience Store

### Cluster 2

In [63]:
toronto_merged.loc[toronto_merged['cluster labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,cluster labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
57,North York,1.0,Baseball Field,Women's Store,Drugstore,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant,Fast Food Restaurant
101,Etobicoke,1.0,Baseball Field,Women's Store,Drugstore,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant,Fast Food Restaurant

### Cluster 3

In [64]:
toronto_merged.loc[toronto_merged['cluster labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,cluster labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,North York,2.0,Park,Fireworks Store,Food & Drink Shop,Donut Shop,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Drugstore
21,York,2.0,Park,Market,Women's Store,Gourmet Shop,Event Space,Empanada Restaurant,Electronics Store,Greek Restaurant,Eastern European Restaurant,Dumpling Restaurant
35,East York,2.0,Park,Convenience Store,Drugstore,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant
61,Central Toronto,2.0,Park,Swim School,Bus Line,Donut Shop,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Drugstore,Dim Sum Restaurant
66,North York,2.0,Park,Bank,Bar,Convenience Store,Drugstore,Distribution Center,Dog Run,Doner Restaurant,Donut Shop,Dumpling Restaurant
85,Scarborough,2.0,Park,Playground,Donut Shop,Dim Sum Restaurant,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant,Women's Store
91,Downtown Toronto,2.0,Park,Playground,Trail,Empanada Restaurant,Electronics Store,Eastern European Restaurant,Dumpling Restaurant,Ethiopian Restaurant,Drugstore,Department Store
98,Etobicoke,2.0,Park,River,Pool,Department Store,Dim Sum Restaurant,Diner,Discount Store,Distribution Center,Dog Run,Doner Restaurant